image: gradle:8.7-jdk17-alpine

stages:
    - build
    - test
    - deploy1
    - deploy2

cache:
    paths:
        - .gradle/wrapper
        - .gradle/caches

build:
    stage: build
    script:
        - git update-index --add --chmod=+x gradlew
        - ./gradlew clean build
    artifacts:
        paths:
            - build/libs/*.jar
        expire_in: 1 week
    only:
        - main

test:
    stage: test
    script: ./gradlew test

deploy1:
    stage: deploy1
    before_script:
        - "command -v ssh-agent >/dev/null || ( apk update && apk add openssh )"
        - eval $(ssh-agent -s)
        - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
        - mkdir -p ~/.ssh
        - chmod 700 ~/.ssh
        - echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts
        - chmod 644 ~/.ssh/known_hosts
    script:
        - ssh -o StrictHostKeyChecking=no ubuntu@"$DEPLOY_SERVER1" 'rm -rf ~/app/build/*.jar'
        - ssh -o StrictHostKeyChecking=no ubuntu@"$DEPLOY_SERVER1" 'mkdir -p ~/app/build'
        - scp build/libs/*.jar ubuntu@"$DEPLOY_SERVER1":~/app/build/demo.jar
        - ssh -o StrictHostKeyChecking=no ubuntu@"$DEPLOY_SERVER1" '~/deploy.sh'
    only:
        - main

deploy2:
    stage: deploy2
    before_script:
        - "command -v ssh-agent >/dev/null || ( apk update && apk add openssh )"
        - eval $(ssh-agent -s)
        - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
        - mkdir -p ~/.ssh
        - chmod 700 ~/.ssh
        - echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts
        - chmod 644 ~/.ssh/known_hosts
    script:
        - ssh -o StrictHostKeyChecking=no ubuntu@"$DEPLOY_SERVER2" 'rm -rf ~/app/build/*.jar'
        - ssh -o StrictHostKeyChecking=no ubuntu@"$DEPLOY_SERVER2" 'mkdir -p ~/app/build'
        - scp build/libs/*.jar ubuntu@"$DEPLOY_SERVER2":~/app/build/demo.jar
        - ssh -o StrictHostKeyChecking=no ubuntu@"$DEPLOY_SERVER2" '~/deploy.sh'
    only:
        - main
