spring:
    application:
        name: server
    datasource:
        driver-class-name: org.mariadb.jdbc.Driver
        url: jdbc:mariadb://localhost:23306/edu
        username: folder
        password: 1234
server:
    port: 8090
